---
- name: Configuring Self Service Network
  hosts: all
  remote_user: root
  vars_files:
  - variable.yml
  tasks:


  - name: Installing the Components
    shell: apt-get -y  install neutron-server neutron-plugin-ml2 neutron-linuxbridge-agent neutron-l3-agent neutron-dhcp-agent neutron-metadata-agent

  - name: Configuring Server Component 
    template: src=templates/neutron_controller.conf.j2 dest=/etc/neutron/neutron.conf

  - name: Configuring Ml2 Plugin
    template: src=templates/ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini

  - name: Configuring Linux Bridge Agent
    template: src=templates/linuxbridge_agent_controller.ini.j2 dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini

  - name: Configure the layer-3 agent 
    template: src=templates/l3_agent.ini.j2 dest=/etc/neutron/l3_agent.ini

  - name: Configure the DHCP agent
    template: src=templates/dhcp_agent.ini.j2 dest=/etc/neutron/dhcp_agent.ini

  - name: Configuring Meta Data Agent
    template: src=templates/metadata_agent.ini.j2 dest=/etc/neutron/metadata_agent.ini

  - name: Configuring Nova To use Neutron networking
    template: src=templates/nova_neutron.conf.j2 dest=/etc/nova/nova.conf

  - name: Finaling Installation
    command: /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron 

  - name: Restarting Compute Api
    service:
      name: nova-api
      state: restarted

  - name: Restarting neutron server
    service:
      name: neutron-server
      state: restarted


  - name: Restarting neutron-linuxbridge-agent
    service:
      name: neutron-linuxbridge-agent
      state: restarted

  - name: Restarting neutron-dhcp-agent
    service:
      name: neutron-dhcp-agent
      state: restarted

  - name: Restarting neutron-metadata-agent
    service:
      name: neutron-metadata-agent
      state: restarted

  - name: Restarting neutron-l3-agent
    service:
      name: neutron-l3-agent
      state: restarted













  
 
...

