- name: Installing And Configuring MongoDB
  hosts: all
  remote_user: root
  vars_files: 
  - variable.yml
  tasks:

  - name: Installing MongoDB server, client and python module
    raw:  apt-get -y install mongodb-server mongodb-clients python-pymongo
  
  - name: Configuring Mongodb  
    replace:
      dest: /etc/mongodb.conf
      regexp: 'bind_ip = 127\.0\.0\.1'
      replace: 'bind_ip = {{remote_ip}}'

  - name: Inserting Configuration
    lineinfile:
     dest: /etc/mongodb.conf
     insertafter: 'bind_ip = {{remote_ip}}'
     line: 'smallfiles = true'

  - name: Stopping Mongodb
    raw: service mongodb stop

  - name: Removing Journal Files
    raw:  rm /var/lib/mongodb/journal/prealloc.*
    ignore_errors: yes
 
  - name: Starting Mongodb Service
    raw:  service mongodb start
