- name: Installing And Configuring RabbitMQ
  hosts: all
  remote_user: root
  vars_files:
  - variable.yml
  tasks:

  - name: Installing RabbitMQ Server
    raw: apt-get -y install rabbitmq-server

  - name: Adding Openstack user
    raw: rabbitmqctl add_user openstack {{password}}

  - name: Give Permissions to Openstack User
    raw: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
